d

diff --git a/cmdline/llxamp-install b/cmdline/llxamp-install
--- a/cmdline/llxamp-install
+++ b/cmdline/llxamp-install
@@ -28,6 +28,16 @@ execute(){
     fi
 }
 
+execute_to_tempfile(){
+    tmpfile=$(mktemp)
+    $@ > $tmpfile
+    if [ $? -ne 0 ]; then
+        echo "Error executing '$@', aborting operation"
+        exit 1
+    fi
+    echo "$tmpfile"
+}
+
 execute_silent(){
     $@ >/dev/null 2>&1
     if [ $? -ne 0 ]; then
@@ -147,12 +157,14 @@ create_target_dir(){
 test_install_pack(){
     [ ! -e "$rpfile_pack" ] && error_menu "invalid install-pack"
     echo Testing archive "$rpfile_pack"
-    contents=$(execute tar -ztf "$rpfile_pack")
-    contents=($(echo $contents|xargs -n1|cut -d'/' -f2|uniq|xargs))
-    need="build-tag httpd php mysql httpd/htdocs/phpMyAdmin"
-    [ ${#contents[@]} -ne 4 ] && error_menu "Invalid contents into $rpfile_pack"
+    tmpfile=$(execute_to_tempfile 'tar -ztf "$rpfile_pack"')
+    need="./build-tag ./httpd ./php ./mysql ./httpd/htdocs/phpMyAdmin"
     for n in $need; do
-        [[ " ${contents[*]} " =~ " $n " ]] && echo "$n found!" || error_menu "$n not found!" 
+        if grep -s $n $tmpfile > /dev/null 2>&1; then
+            echo "$n found!" 
+        else 
+            error_menu "$n not found!"
+        fi
     done
 }
 
